### ISSUE TITLE
Roadmap for master 0.9 and master 1.0

### ISSUE THREAD

**Issue by dl9rdz** [dl9rdz/rdz_ttgo_sonde#162]
Update: master 0.9 is out.

Plan is to have a final master 1.0 by end of 2021, open issues that possibly (likely?) will be added until then:

Decoders
- [x] Check DFM data quality (clear all data and wait for data completion if a new sonde starts being received) (at least partially done already)

Board and display support
- [ ] Add support for M5STACK Core Gray, test and enhance version for M5STACK Core Due
- [ ] Add compass display for OLED display (merge existing code from somewhere...)
- [ ] Fine-tune screen2 for landscape TFT
- [ ] Optimize screen 3 for portrait TFT (current version is very rudimentary, contributions welcome!)
- [ ] Add better screen 4/5 of for large ILI9341 TFT (hopefully will get a contribution for that) (we have a new screen5 already)
- [ ] Add new screen 6/7 for small but high resolution ILI9342 TFT (M5STACK)

Network interfaces
- [ ] Test if altitudemode in KML works fine also with LotusMap live feed
- [ ] Add features to integrated HTML map (show more info like time of last frame)

Documentation
- [ ] Update documentation (and add documentation how to easily contribute to documentation) #88
- [ ] Add wiring diagrams to documentation

Others
- [ ] Offline maps for rdzwx-go
- [x] Reorganize flash layout: More space for code, separate partition for TFT fonts (exclude them from OTA updates), smaller partition for file system. 
- [ ] User friendly flash tool (add features, create executable with pyinstaller for Mac/Windows)
- [x] MAYBE: Check if the new arduino esp32 idf version can be used (seems to use much more RAM, so maybe not practical?) (not yet available for platform io yet anyway, so maybe for post-master-1.0)

These items made it into master 0.9:
- [x] Check RS41 data quality (clear subframe buffer if a new sonde is received)
- [x] Possibly enhance humidity meteo data for RS41 (no priority for me, will accept contributions) #152
- [x] Show RINEX status on web interface #65
- [x] Maybe replace M10 and M20 by a single M10/M20 entry in frequency config (both use exactly the same decoder)
- [x] Fix line spacing on TFT during OTA update
- [x] Test MQTT interface and close open issue #58
- [x] Enable aprs/radiosondy upload of data
- [x] Finish SondeHub interface
- [x] Redesign qrg.html to make network message smaller (less out-of-memory issues)
- [x] Mabye do the same for config.html (same reason)
- [x] Move SondeHub static gps position to global static gps position that is also used for compass on TFT if no GPS available
- [x] OTA updates that also update (parts of the ) data: .js/.css/.html
- [x] (Maybe) download of active scan frequencies from sondehub? #120

**Comment by LukePrior** [comment]
Can we get a new master release from the devel branch as 0.9 has several bugs in regards to SondeHub uploading.

**Comment by TarmoKolli** [comment]
Maybe it would be possible to add SD card support and write the sonde location information to the card as well. I'm looking for landed sondes and would be very interested in the all latest GPS location points.

**Comment by LukePrior** [comment]
> Maybe it would be possible to add SD card support and write the sonde location information to the card as well. I'm looking for landed sondes and would be very interested in the all latest GPS location points.

The best way to do this would be storing the MQTT messages on an external device or you could upload the data to SondeHub and use the APIs to download it.

**Comment by TarmoKolli** [comment]
> > Maybe it would be possible to add SD card support and write the sonde location information to the card as well. I'm looking for landed sondes and would be very interested in the all latest GPS location points.
> 
> The best way to do this would be storing the MQTT messages on an external device or you could upload the data to SondeHub and use the APIs to download it.

I send my received signals to both tracker.sondehub.org and radiosondy.info servers, but since I don't have a HAM license, I send data every 45 seconds. The servers are blocking me from sending data at shorter intervals.
Maintaining a separate data server, raspberry or pc would reduce the benefits of rdz_ttgo.

**Comment by dl9rdz** [comment]
This has become somewhat outdated.

Ongoing work on an upgrade in the new dev branch with new esp32 idf will result in a version main1.0 later this year.  Maybe a new roadmap for the future will be planned based on that....
